name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SLN_FILE: .\SemanticReleaesPoc\SemanticReleaesPoc.sln

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore $SLN_FILE
    - name: Build
      run: dotnet build $SLN_FILE --no-restore
    - name: Test
      run: dotnet test $SLN_FILE --no-build --verbosity normal
